### ISSUE TITLE
Подключение к сервису ошибка

### ISSUE THREAD

**Issue by Mosokna** [oknosoft/windowbuilder-parametric#74]
При подключении к сервису (попытка считать справочники, возвращается ошибка.
TypeError: Cannot read property 'filter' of undefined
    at cat (/var/www/windowbuilder-parametric/index.js:327:41)
    at get (/var/www/windowbuilder-parametric/index.js:364:20)
    at dispatch (/var/www/windowbuilder-parametric/node_modules/koa-compose/index.js:44:32)
    at /var/www/windowbuilder-parametric/node_modules/koa-compose/index.js:36:12
    at /var/www/windowbuilder-parametric/node_modules/koa-better-router/index.js:547:46
    at dispatch (/var/www/windowbuilder-parametric/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at log (/var/www/windowbuilder-parametric/index.js:186:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
)

**Comment by unpete** [comment]
Что имеете в виду под "подключением к сервису"?
Только что проверил запрос `GET /prm/cat` от имени пользователя `mosokna` - получил адекватный ответ.

**Comment by Mosokna** [comment]
Вот мои реквизиты подключения.
  "scheme": "https",
  "host": "crystallit.oknosoft.ru",
  "port": 443,
  "login": "mosokna",
  "password": "********"(пароль не показываю),
  "suffix": "27"

Кидаю его в кеш, и делаю запрос.
Рез = Новый Структура("data", ЗапросКСервису("get", "prm/cat/clrs,nom,inserts", Кеш));
Результат возвращает error=Истина,
и месседж, который я выше переслал.

**Comment by unpete** [comment]
ошибку воспроизвёл - разбираюсь

**Comment by unpete** [comment]
https://github.com/oknosoft/windowbuilder-parametric/commit/523f6f827e395b4715f9abd3f3e398aaf23053c9
Проверяйте - должно работать.

**Comment by Mosokna** [comment]
Да, все получилось, спасибо
